dataset:
    name: cifar10
    root: /home/zhfeing/datasets/cifar
    img_w: 32
    img_h: 32

training:
    optimizer:
        name: SGD
        lr: 0.05
        weight_decay: 5.0e-4
        momentum: 0.9

    lr_decay_epochs: [150, 180, 210]
    lr_decay_rate: 0.1
    batch_size: 64
    num_workers: 8
    epochs: 240
    seed: 1029
    save_ep_freq: 1
    print_iter_freq: 10

validation:
    batch_size: 128
    num_workers: 8

kd:
    student:
        name: resnet56
    teacher:
        name: wrn_40_2
        checkpoint: run/cifar-10/seed-1029/valina/train_wrn_40_2/ckpt/epoch_240.pth
    loss_weights:
        classify_weight: 0.1
        kd_weight: 0.9
        other_loss_weight: 0.05

kd_loss:
    KD_T: 4

    name: HierarchicalLoss
    layer_cluster_info:
        layer1: run/cifar-10/seed-1029/cluster-tree-wrn_40_2/block1-merge.json
        layer2: run/cifar-10/seed-1029/cluster-tree-wrn_40_2/block2-merge.json

